### ISSUE TITLE
Unable to run nptel-dl

### ISSUE THREAD

**Issue by abshek** [nishanthvijayan/nptel-dl#1]
- Had to do a `go get <gitpath>` first, else `go install <gitpath>` was throwing error
- After a successful `go get <gitpath>`, `nptel-dl` command could not be found

**Comment by nishanthvijayan** [comment]
Hi Abhishek, I've created a release page from where you can download the binaries directly. This way you don't have to worry about installing go & any of its env variables.
You can download the binaries from: https://github.com/nishanthvijayan/nptel-dl/releases
